### ISSUE TITLE
Some links in README don't work

### ISSUE THREAD

**Issue by acocac** [2i2c-org/hub-user-image-template#15]
### Context

The links to the following bullet points in the README file don't work. 

- [How to create and use a custom user image for your hub](https://github.com/2i2c-org/hub-user-image-template#how-to-create-and-use-a-custom-user-image-for-your-hub-gear)
  - [Use this template](https://github.com/2i2c-org/hub-user-image-template#1-use-this-template)
  - [Hook the new repository to quay.io](https://github.com/2i2c-org/hub-user-image-template#2-hook-the-new-repository-to-quayio)
  - [Enable image push to quay.io](https://github.com/2i2c-org/hub-user-image-template#3-enable-image-push-to-quayio)
  - [Enable quay.io image push for build.yaml](https://github.com/2i2c-org/hub-user-image-template#enable-quayio-image-push-for-buildyaml)
  - [Enable quay.io image push for test.yaml](https://github.com/2i2c-org/hub-user-image-template#enable-quayio-image-push-for-testyaml)
  - [Customize the image](https://github.com/2i2c-org/hub-user-image-template#4-customize-the-image)
  - [Build and push the image](https://github.com/2i2c-org/hub-user-image-template#5-build-and-push-the-image)
  - [Connect the hub with this user image](https://github.com/2i2c-org/hub-user-image-template#6-connect-the-hub-with-this-user-image)
  - [Test the new image](https://github.com/2i2c-org/hub-user-image-template#7-test-the-new-image)
 - [Push image to a registry other than Quay.io](https://github.com/2i2c-org/hub-user-image-template#push-image-to-a-registry-other-than-quayio-cloud)

Also the links within [Overall workflow](https://github.com/2i2c-org/hub-user-image-template#overall-workflow)

### Proposal

I'd suggest to remove or comment them if the documentation is WIP.

**Comment by GeorgianaElena** [comment]
Thanks a lot for spotting this @acocac! The instructions in the readme were indeed moved to https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide.html and unfortunately the readme wasn't updated properly.

I just opened https://github.com/2i2c-org/hub-user-image-template/pull/16 to fix this!
