### ISSUE TITLE
Link in README not working

### ISSUE THREAD

**Issue by jbusecke** [2i2c-org/hub-user-image-template#31]
A researcher at LEAP just noticed that the link in the readme https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide.html is not working anymore. Does anyone here know what the correct replacement is?

**Comment by jnywong** [comment]
Hey @jbusecke, this has been replaced with [https://docs.2i2c.org/admin/howto/environment/customize-image/](https://docs.2i2c.org/admin/howto/environment/customize-image/).

I can setup a redirect from the old link to the new link 👍

**Comment by jnywong** [comment]
Hey I've applied the redirect but it works for https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide _without_ the `.html` extension. Is that okay? If not I can look into it a bit more

**Comment by jbusecke** [comment]
Thanks for that @jnywong. Unfortunately this does not work with the current version of the README here. Unless this is referenced somewhere else in a different way, we might as well put the new link into the README (see #32)?

**Comment by jnywong** [comment]
Ah I see more clearly which README you are referencing.

- https://docs.2i2c.org/admin/howto/environment/customize-image/ is associated with [this new template ](https://github.com/2i2c-org/example-inherit-from-community-image)
- https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide was associated with the previous template https://github.com/2i2c-org/hub-user-image-template

@jbusecke can I get your input into whether we should deprecate the latter `hub-user-image-template-guide` and recommend supporting the `example-inherit-from-community-image` method?

**Comment by jbusecke** [comment]
Hey @jnywong, just coming back to this topic. Thanks for the nice write up. This will definitely save me a lot of time. Re your question above, I think this is not an either or question. I have used both cases (and templates)! Could I suggest resurrecting the old docs in a separate section with an explanation why the other should be preferred? As far as I understand @yuvipanda made the argument that this is more sustainable in the long run due to the maintenance done upstream, which makes tons of sense. I personally think that for more advanced users there might be a case for building from scratch (e.g. to save on downloading time).

**Comment by jbusecke** [comment]
Btw just linked to your amazing instructions in our [docs](https://github.com/leap-stc/leap-stc.github.io/pull/173). Many thanks!

**Comment by jnywong** [comment]
> Hey @jnywong, just coming back to this topic. Thanks for the nice write up. This will definitely save me a lot of time. Re your question above, I think this is not an either or question. I have used both cases (and templates)! Could I suggest resurrecting the old docs in a separate section with an explanation why the other should be preferred? As far as I understand @yuvipanda made the argument that this is more sustainable in the long run due to the maintenance done upstream, which makes tons of sense. I personally think that for more advanced users there might be a case for building from scratch (e.g. to save on downloading time).

Thank you for your thoughtful response @jbusecke !

Yes, I was hesitant about removing references to this repo entirely and the user story you put forward makes a a lot of sense!

I'll make the README more clear and add references back into the 2i2c Service Guide to signpost for more advanced users :)
